# src/DDQBundle/Resources/config/validation.yml
CNAMTS\DDQ\Bundle\Entity\DdqCampagne:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [ libelle ]
        message: "Ce libellé est déjà utilisé"
  properties:
    libelle:
      - NotBlank:
          message: "Vous devez renseigner un libellé"
      - Length:
          max: 32
          maxMessage: 'le libellé ne peut pas faire plus de 32 caractères'
    datedebut:
      - Date:
      - NotBlank:
          message: "Vous devez renseigner une date de début"
    #            - LesserThanOrEqual: today UTC
    datefin:
      - Date:
      - NotBlank:
          message: "Vous devez renseigner une date de fin"
      - GreaterThanOrEqual: today UTC

CNAMTS\DDQ\Bundle\Entity\DdqQuestionnaireParking:
  properties:
    adresse:
      - NotBlank:
          message: "Vous devez préciser votre adresse"
      - Length:
          max: 255
          maxMessage: "l'adresse ne peut pas faire plus de 255 caractères"
    signature:
      - NotBlank:
          message: "Vous devez signer le formulaire afin de le soumettre"
CNAMTS\DDQ\Bundle\Entity\DdqQuestionnaireRTT:
  properties:

    idDdqContrat:
      - NotBlank:
          message: "Veuillez choisir votre contrat temps plein"
      - NotNull:
          message: "Vous devez choisir un type de contrat"
    reprisetp:
      - NotBlank:
          message: "Veuillez choisir votre contrat temps plein"
      - NotNull:
          message: "Vous devez choisir un type de contrat"
    formule:
      - NotBlank:
          message: "Veuillez choisir votre contrat temps plein"
      - NotNull:
          message: "Vous devez choisir un type de contrat"

    formule1s:
      - NotBlank:
          message: "Veuillez choisir votre contrat temps plein"
      - NotNull:
          message: "Vous devez choisir un type de contrat"

    formule1j:
      - NotBlank:
          message: "Veuillez choisir votre contrat temps plein"
      - NotNull:
          message: "Vous devez choisir un type de contrat"



    signature:
      - NotBlank:
          message: "Vous devez signer le formulaire afin de le soumettre"
      - NotNull:
          message: "Vous devez choisir un type de contrat"